baseURL = "https://oldbig9.github.io"
languageCode = "zh_CN"
title = "oldbig9"
theme = "m10c"
buildFuture = true
paginate = 12

[taxonomies]
tag = "tags"
category = "categories"

###########m10c###########
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "songci"
    name = "宋词"
    url = "/songci/"
    weight = 2
  [[menu.main]]
    identifier = "tech"
    name = "技术"
    url = "/tech/"
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4

[params]
  author = "oldbig9"
  avatar = "images/dog.jpg"
  description = " "
  menu_item_separator = " | "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/oldbig9"

  # Default theme
  # [params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
