baseURL = "https://oldbig9.github.io/"
title = "OLDBIG9`小仓库"
author = "Whatever"
copyright = ""
paginate = 10
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true

[module]
  [module.hugoVersion]
    extended = true
    min = "v0.95.0"
  [[module.imports]]
    path = "github.com/tomowang/hugo-theme-tailwind"
    disable = false

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "docs"
  toc = false

  [params.header]
    logo = "aoteman.jpg"

  [params.footer]
    since = 2023
    poweredby = true

[menu]

  [[menu.main]]
    identifier = "Docs"
    name = "技术"
    pageRef = "/"
    weight = 1

   [[menu.main]]
    identifier = "Songci"
    name = "宋词"
    pageRef = "/songci"
    weight = 2

   [[menu.main]]
    identifier = "Note"
    name = "笔记"
    pageRef = "/note"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    pageRef = "/about"
    weight = 10
  [[menu.main]]
    identifier = "linqianxi"
    name = "林浅喜"
    pageRef = "https://space.bilibili.com/430967976"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"